apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qua-azure-git-test
  janus-idp.io/tekton: qua-azure-git-test
  backstage.io/kubernetes-id: qua-azure-git-test
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qua-azure-git-test
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
